"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersController = void 0;
const msRest = __importStar(require("@azure/ms-rest-js"));
const Mappers = __importStar(require("../models/usersControllerMappers"));
const Parameters = __importStar(require("../models/parameters"));
/** Class representing a UsersController. */
class UsersController {
    /**
     * Create a UsersController.
     * @param {LungscanAPIContext} client Reference to the service client.
     */
    constructor(client) {
        this.client = client;
    }
    getAll(options, callback) {
        return this.client.sendOperationRequest({
            options
        }, getAllOperationSpec, callback);
    }
    createOne(body, options, callback) {
        return this.client.sendOperationRequest({
            body,
            options
        }, createOneOperationSpec, callback);
    }
    getById(id, options, callback) {
        return this.client.sendOperationRequest({
            id,
            options
        }, getByIdOperationSpec, callback);
    }
    getUserByUsername(body, options, callback) {
        return this.client.sendOperationRequest({
            body,
            options
        }, getUserByUsernameOperationSpec, callback);
    }
}
exports.UsersController = UsersController;
// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getAllOperationSpec = {
    httpMethod: "GET",
    path: "api/users",
    responses: {
        200: {},
        default: {}
    },
    serializer
};
const createOneOperationSpec = {
    httpMethod: "POST",
    path: "api/users",
    requestBody: {
        parameterPath: "body",
        mapper: {
            required: true,
            serializedName: "body",
            type: {
                name: "Object"
            }
        }
    },
    responses: {
        201: {},
        default: {}
    },
    serializer
};
const getByIdOperationSpec = {
    httpMethod: "GET",
    path: "api/users/{id}",
    urlParameters: [
        Parameters.id
    ],
    responses: {
        200: {},
        default: {}
    },
    serializer
};
const getUserByUsernameOperationSpec = {
    httpMethod: "POST",
    path: "api/users/login",
    requestBody: {
        parameterPath: "body",
        mapper: Object.assign(Object.assign({}, Mappers.LoginDto), { required: true })
    },
    responses: {
        201: {},
        default: {}
    },
    serializer
};
//# sourceMappingURL=usersController.js.map