"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreatePatientDto = exports.LoginDto = void 0;
exports.LoginDto = {
    serializedName: "LoginDto",
    type: {
        name: "Composite",
        className: "LoginDto",
        modelProperties: {
            username: {
                required: true,
                serializedName: "username",
                type: {
                    name: "String"
                }
            },
            password: {
                required: true,
                serializedName: "password",
                type: {
                    name: "String"
                }
            }
        }
    }
};
exports.CreatePatientDto = {
    serializedName: "CreatePatientDto",
    type: {
        name: "Composite",
        className: "CreatePatientDto",
        modelProperties: {
            firstname: {
                required: true,
                serializedName: "firstname",
                type: {
                    name: "String"
                }
            },
            lastname: {
                required: true,
                serializedName: "lastname",
                type: {
                    name: "String"
                }
            },
            dOB: {
                required: true,
                serializedName: "DOB",
                type: {
                    name: "Date"
                }
            }
        }
    }
};
//# sourceMappingURL=mappers.js.map