"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreatePatientDto = void 0;
var mappers_1 = require("../models/mappers");
Object.defineProperty(exports, "CreatePatientDto", { enumerable: true, get: function () { return mappers_1.CreatePatientDto; } });
//# sourceMappingURL=patientsControllerMappers.js.map