"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LoginDto = void 0;
var mappers_1 = require("../models/mappers");
Object.defineProperty(exports, "LoginDto", { enumerable: true, get: function () { return mappers_1.LoginDto; } });
//# sourceMappingURL=usersControllerMappers.js.map