"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.LungscanAPIMappers = exports.LungscanAPIModels = exports.LungscanAPIContext = exports.LungscanAPI = void 0;
const Models = __importStar(require("./models"));
exports.LungscanAPIModels = Models;
const Mappers = __importStar(require("./models/mappers"));
exports.LungscanAPIMappers = Mappers;
const operations = __importStar(require("./operations"));
const lungscanAPIContext_1 = require("./lungscanAPIContext");
Object.defineProperty(exports, "LungscanAPIContext", { enumerable: true, get: function () { return lungscanAPIContext_1.LungscanAPIContext; } });
class LungscanAPI extends lungscanAPIContext_1.LungscanAPIContext {
    /**
     * Initializes a new instance of the LungscanAPI class.
     * @param [options] The parameter options
     */
    constructor(options) {
        super(options);
        this.usersController = new operations.UsersController(this);
        this.patientsController = new operations.PatientsController(this);
        this.filmsController = new operations.FilmsController(this);
        this.resultsController = new operations.ResultsController(this);
        this.fileController = new operations.FileController(this);
    }
}
exports.LungscanAPI = LungscanAPI;
__exportStar(require("./operations"), exports);
//# sourceMappingURL=lungscanAPI.js.map